import type { Icon as PhosphorIcon, IconProps } from '@phosphor-icons/react';
import {
  ChatCircleTextIcon,
  LifebuoyIcon,
  HeadsetIcon,
  ShieldCheckIcon,
  ArrowRightIcon,
  ArrowUpRightIcon,
  LinkedinLogoIcon,
  XLogoIcon,
  YoutubeLogoIcon,
  InstagramLogoIcon,
  FacebookLogoIcon,
  GithubLogoIcon,
  AppleLogoIcon,
  GooglePlayLogoIcon,
  DeviceMobileIcon,
  BuildingsIcon,
  StackIcon,
  TargetIcon,
  BookOpenIcon,
  ChartLineUpIcon,
  TreeStructureIcon,
  TruckIcon,
  LockIcon,
  ChatsCircleIcon,
  TerminalWindowIcon,
  SealCheckIcon,
  CloudIcon,
  ScalesIcon,
  BankIcon,
  LeafIcon,
  HandshakeIcon,
  GlobeIcon,
  HandHeartIcon,
  MedalIcon,
  FlagIcon,
  TrendUpIcon,
  MapPinIcon,
  ClockIcon,
  PhoneIcon,
  CookieIcon,
  CaretDownIcon,
  ArrowUpIcon,
  SunIcon,
  MoonIcon,
  DatabaseIcon,
  TranslateIcon,
  QuestionIcon,
  FilesIcon,
  WarningIcon,
  CheckCircleIcon,
  CopyIcon,
  SparkleIcon,
  FileTextIcon,
  PulseIcon,
  CircleIcon,
  MonitorPlayIcon,
  CodeIcon,
  TableIcon,
  KeyIcon,
  UsersThreeIcon,
  BugIcon,
  ArrowsClockwiseIcon,
  BrainIcon,
  ClockCounterClockwiseIcon,
  ClipboardTextIcon,
  DetectiveIcon,
  WheelchairIcon,
  CreditCardIcon,
  ListChecksIcon,
  InfoIcon,
  IdentificationCardIcon,
} from '@phosphor-icons/react';

/** JSON'da string olarak geçen ikon adlarının kaydı. Yeni ikon için buraya bir satır ekleyin. */
export const ICONS: Record<string, PhosphorIcon> = {
  ChatCircleText: ChatCircleTextIcon,
  Lifebuoy: LifebuoyIcon,
  Headset: HeadsetIcon,
  ShieldCheck: ShieldCheckIcon,
  ArrowRight: ArrowRightIcon,
  ArrowUpRight: ArrowUpRightIcon,
  LinkedinLogo: LinkedinLogoIcon,
  XLogo: XLogoIcon,
  YoutubeLogo: YoutubeLogoIcon,
  InstagramLogo: InstagramLogoIcon,
  FacebookLogo: FacebookLogoIcon,
  GithubLogo: GithubLogoIcon,
  AppleLogo: AppleLogoIcon,
  GooglePlayLogo: GooglePlayLogoIcon,
  DeviceMobile: DeviceMobileIcon,
  Buildings: BuildingsIcon,
  Stack: StackIcon,
  Target: TargetIcon,
  BookOpen: BookOpenIcon,
  ChartLineUp: ChartLineUpIcon,
  TreeStructure: TreeStructureIcon,
  Truck: TruckIcon,
  Lock: LockIcon,
  ChatsCircle: ChatsCircleIcon,
  TerminalWindow: TerminalWindowIcon,
  SealCheck: SealCheckIcon,
  Cloud: CloudIcon,
  Scales: ScalesIcon,
  Bank: BankIcon,
  Leaf: LeafIcon,
  Handshake: HandshakeIcon,
  Globe: GlobeIcon,
  HandHeart: HandHeartIcon,
  Medal: MedalIcon,
  Flag: FlagIcon,
  TrendUp: TrendUpIcon,
  MapPin: MapPinIcon,
  Clock: ClockIcon,
  Phone: PhoneIcon,
  Cookie: CookieIcon,
  CaretDown: CaretDownIcon,
  ArrowUp: ArrowUpIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Database: DatabaseIcon,
  Translate: TranslateIcon,
  Question: QuestionIcon,
  Files: FilesIcon,
  Warning: WarningIcon,
  CheckCircle: CheckCircleIcon,
  Copy: CopyIcon,
  Sparkle: SparkleIcon,
  FileText: FileTextIcon,
  Pulse: PulseIcon,
  Circle: CircleIcon,
  MonitorPlay: MonitorPlayIcon,
  Code: CodeIcon,
  Table: TableIcon,
  Key: KeyIcon,
  UsersThree: UsersThreeIcon,
  Bug: BugIcon,
  ArrowsClockwise: ArrowsClockwiseIcon,
  Brain: BrainIcon,
  ClockCounterClockwise: ClockCounterClockwiseIcon,
  ClipboardText: ClipboardTextIcon,
  Detective: DetectiveIcon,
  Wheelchair: WheelchairIcon,
  CreditCard: CreditCardIcon,
  ListChecks: ListChecksIcon,
  Info: InfoIcon,
  IdentificationCard: IdentificationCardIcon,
};

export function Icon({ name, ...props }: { name?: string } & IconProps) {
  const Cmp = (name && ICONS[name]) || QuestionIcon;
  if (name && !ICONS[name] && import.meta.env.DEV) console.warn(`[engine] Bilinmeyen ikon: "${name}"`);
  return <Cmp {...props} />;
}
